package fxTilastopankki.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.26 14:38:42 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** testLueTiedosto31 */
  @Test
  public void testLueTiedosto31() {    // Joukkueet: 31
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue joukkue1 = new Joukkue("test", 1); 
    Joukkue joukkue2 = new Joukkue("test", 2); 
    Joukkue joukkue3 = new Joukkue("test", 3); 
    joukkueet.lisaaJoukkue(joukkue1); 
    joukkueet.lisaaJoukkue(joukkue2); 
    joukkueet.lisaaJoukkue(joukkue3); 
    joukkueet.tallenna("joukkueettesti.dat", "pelaajattesti.dat"); 
    joukkueet.tyhjenna(); 
    joukkueet.lueTiedosto("joukkuetesti.dat"); 
    assertEquals("From: Joukkueet line: 43", 3, joukkueet.getJoukkueet().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSeuraavaId65 */
  @Test
  public void testSeuraavaId65() {    // Joukkueet: 65
    Joukkueet test = new Joukkueet(); 
    assertEquals("From: Joukkueet line: 67", 1, test.seuraavaId()); 
    Joukkue joukkue1 = new Joukkue(); 
    joukkue1.setId(1); 
    test.lisaaJoukkue(joukkue1); 
    assertEquals("From: Joukkueet line: 71", 2, test.seuraavaId()); 
    Joukkue joukkue2 = new Joukkue(); 
    test.lisaaJoukkue(joukkue2); 
    joukkue2.setId(4); 
    assertEquals("From: Joukkueet line: 75", 5, test.seuraavaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiJoukkue107 */
  @Test
  public void testEtsiJoukkue107() {    // Joukkueet: 107
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue joukkue1 = new Joukkue("test1", 1); 
    Joukkue joukkue2 = new Joukkue("test2", 2); 
    Joukkue joukkue3 = new Joukkue("test3", 3); 
    Joukkue joukkue4 = new Joukkue("test4", 4); 
    joukkueet.lisaaJoukkue(joukkue1); 
    joukkueet.lisaaJoukkue(joukkue2); 
    joukkueet.lisaaJoukkue(joukkue3); 
    joukkueet.lisaaJoukkue(joukkue4); 
    assertEquals("From: Joukkueet line: 117", true, joukkueet.etsiJoukkue(1)); 
    assertEquals("From: Joukkueet line: 118", false, joukkueet.etsiJoukkue(5)); 
    assertEquals("From: Joukkueet line: 119", true, joukkueet.etsiJoukkue(2)); 
    assertEquals("From: Joukkueet line: 120", false, joukkueet.etsiJoukkue(6)); 
    assertEquals("From: Joukkueet line: 121", true, joukkueet.etsiJoukkue(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna155 */
  @Test
  public void testTallenna155() {    // Joukkueet: 155
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue joukkue1 = new Joukkue("test", 1); 
    Joukkue joukkue2 = new Joukkue("test", 2); 
    Joukkue joukkue3 = new Joukkue("test", 3); 
    joukkueet.lisaaJoukkue(joukkue1); 
    joukkueet.lisaaJoukkue(joukkue2); 
    joukkueet.lisaaJoukkue(joukkue3); 
    joukkueet.tallenna("joukkuetesti.dat", "pelaajattesti.dat"); 
    joukkueet.tyhjenna(); 
    joukkueet.lueTiedosto("joukkueet.dat"); 
    assertEquals("From: Joukkueet line: 167", 3, joukkueet.getJoukkueet().size()); 
    assertEquals("From: Joukkueet line: 168", 2, joukkueet.getJoukkueet().get(1).getId()); 
  } // Generated by ComTest END
}