package fxTilastopankki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.12 16:34:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testParse92 */
  @Test
  public void testParse92() {    // Joukkue: 92
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("1|test|"); 
    joukkue.toString().equals("1|test|"); 
  } // Generated by ComTest END
}