package fxTilastopankki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.12 16:34:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** testSeuraavaId47 */
  @Test
  public void testSeuraavaId47() {    // Joukkueet: 47
    Joukkueet test = new Joukkueet(); 
    assertEquals("From: Joukkueet line: 49", 1, test.seuraavaId()); 
    Joukkue joukkue1 = new Joukkue(); 
    joukkue1.setId(1); 
    test.lisaaJoukkue(joukkue1); 
    assertEquals("From: Joukkueet line: 53", 2, test.seuraavaId()); 
    Joukkue joukkue2 = new Joukkue(); 
    test.lisaaJoukkue(joukkue2); 
    joukkue2.setId(4); 
    assertEquals("From: Joukkueet line: 57", 5, test.seuraavaId()); 
  } // Generated by ComTest END
}