package fxTilastopankki.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.26 14:36:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testLueTiedosto82 */
  @Test
  public void testLueTiedosto82() {    // Joukkue: 82
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue joukkue = new Joukkue(); 
    joukkue.setId(1); 
    joukkueet.lisaaJoukkue(joukkue); 
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.testiTiedot(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("2|test|1|1|1|1|1|1|"); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("1|test|1|1|1|1|1|1|"); 
    Pelaaja pelaaja4 = new Pelaaja(); 
    pelaaja4.parse("3|test|1|1|1|1|1|1|"); 
    joukkue.lisaaPelaaja(pelaaja1); 
    joukkue.lisaaPelaaja(pelaaja2); 
    joukkue.lisaaPelaaja(pelaaja3); 
    joukkue.lisaaPelaaja(pelaaja4); 
    joukkueet.tallenna("joukkuetesti.dat", "pelaajatesti.dat"); 
    joukkue.tyhjenna(); 
    joukkue.lueTiedosto("pelaajatesti.dat"); 
    assertEquals("From: Joukkue line: 103", 2, joukkue.getPelaajat().length); 
    assertEquals("From: Joukkue line: 104", 1, joukkue.getPelaajat()[0].getId()); 
    assertEquals("From: Joukkue line: 105", 1, joukkue.getPelaajat()[1].getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse129 */
  @Test
  public void testParse129() {    // Joukkue: 129
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("1|test|"); 
    joukkue.toString().equals("1|test|"); 
  } // Generated by ComTest END
}