package fxTilastopankki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.12 16:34:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajanTiedotControllerTest {
}