package fxTilastopankki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTilastopankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.12 16:34:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testParse145 */
  @Test
  public void testParse145() {    // Pelaaja: 145
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1|test|1|1|1|1|1|1|"); 
    pelaaja.toString().equals("1|test|1|1|1|1|1|1|"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString180 */
  @Test
  public void testToString180() {    // Pelaaja: 180
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1|test|1|1|1|1|1|1|"); 
    assertEquals("From: Pelaaja line: 183", true, pelaaja.toString().startsWith("1|test|1")); 
  } // Generated by ComTest END
}